# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'


- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'npm install'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
  displayName: 'build'


- task: CopyFiles@2
  inputs:
    contents: 'public/**' 
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true 
  displayName: 'copy built site'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'build' 
  displayName: ' Publish Artifacts'

- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/public'
    azureSubscription: 'Pleavitt MSDN(f75ee177-28bf-41b9-9e3e-8855bac93f17)'
    Destination: 'AzureBlob'
    storage: 'simplelifestorage'
    ContainerName: '$web'
  displayName: 'Copy to Azure'


